# QIII

**Julien Wist**<br>
*Universidad del Valle*<br>
*2016*


# Angular Momentum

The angular momentum is defined classically as:

$$
\mathbf{L} = \mathbf{r} \times \mathbf{p}
$$

Where $\mathbf{L}$, $\mathbf{r}$ and $\mathbf{p}$ are vectors in $\mathbb{R}^3$ so we can write

$$
\mathbf{L} = (L_x, L_y, Lz)
$$

where $L_x$, $L_y$ and $Lz$ are the projections of the vector on the three cartesian axis.

<img src="../img/angularMomentum.png" width="200">

<center>from Levine p. 102</center>


## cross product
$$
\mathbf{r} = \mathbf{i}x + \mathbf{j}y + \mathbf{k}z
$$
$$
\mathbf{v} = \frac{\partial r}{\partial t} = \mathbf{i}\frac{\partial x}{\partial t} + \mathbf{j}\frac{\partial y}{\partial t} + \mathbf{k}\frac{\partial z}{\partial t}
$$

Since 

$$
\mathbf{L} = \mathbf{r} \times \mathbf{p}
$$

we can evaluate the cross product

$$
\mathbf{L} = \left|\begin{array}{ccc} \mathbf{i} & \mathbf{j} & \mathbf{k}\\ x&y&z \\ p_x & p_y & p_z \end{array}\right| = \mathbf{i} \left|\begin{array}{cc} y & z \\ p_y & p_z \end{array}\right| -\mathbf{i} \left|\begin{array}{cc} x & z \\ p_x & p_z \end{array}\right| +
\mathbf{k} \left|\begin{array}{cc} x & y \\ p_x & p_y \end{array}\right|
$$

$$
L_x = yp_z - zp_y, L_y = zp_x - xp_z, L_z = xp_y - yp_x
$$


## angular momentum operators

In order to find out the corresponding quantum operators we used the relations (given by Schrödinger):

$$
\hat{x} = x, \hat{p}_x = -i \hbar \frac{\partial}{\partial x}
$$

by substitution we readily find:

$$
\hat{L}_x = -i\hbar \left(y \frac{\partial}{\partial z} - z \frac{\partial}{\partial y} \right)
$$
$$
\hat{L}_y = -i\hbar \left(z \frac{\partial}{\partial x} - x \frac{\partial}{\partial z} \right)
$$
$$
\hat{L}_z = -i\hbar \left(x \frac{\partial}{\partial y} - y \frac{\partial}{\partial x} \right)
$$

by noting that

$$
y\hat{p}_z = \hat{p}_z y
$$




## the magnitude operator
From the 3 projections we can build the operator for the magnitud of the momentum

$$
\hat{L}^2 = \hat{L}_x^2+ \hat{L}_y^2 + \hat{L}_z^2
$$

## commutation rules

Using 
$$
\hat{L}_x = -i\hbar \left(y \frac{\partial}{\partial z} - z \frac{\partial}{\partial y} \right)
$$
$$
\hat{L}_y = -i\hbar \left(z \frac{\partial}{\partial x} - x \frac{\partial}{\partial z} \right)
$$

we can compute 

$$
[\hat{L}_x,\hat{L}_y]
$$

$$
\hat{L}_x\hat{L}_y f = -\hbar^2\left( y \frac{\partial f}{\partial x} +yz \frac{\partial^2 f}{\partial z\partial x} - yx \frac{\partial^2 f}{\partial^2 z} - z^2 \frac{\partial^2 f}{\partial y\partial x} + zx \frac{\partial^2 f}{\partial y\partial z}\right)
$$


$$
\hat{L}_y\hat{L}_x f = -\hbar^2\left( zy \frac{\partial^2 f}{\partial x\partial z} - z^2 \frac{\partial^2 f}{\partial x\partial y} - xy \frac{\partial^2 f}{\partial^2 z} + x \frac{\partial f}{\partial y} + xz \frac{\partial^2 f}{\partial z\partial y}\right)
$$

$$
\hat{L}_x\hat{L}_y f - \hat{L}_y\hat{L}_x f = -\hbar^2\left(y \frac{\partial f}{\partial x} - x \frac{\partial f}{\partial y}  \right)
$$

$$
[\hat{L}_x,\hat{L}_y] = -i\hbar \hat{L}_z
$$

Repeating this with all the operators we find:

$$
[\hat{L}_y,\hat{L}_z] = -i\hbar \hat{L}_x
$$

$$
[\hat{L}_z,\hat{L}_x] = -i\hbar \hat{L}_y
$$

and

$$
[\hat{L}^2,\hat{L}_x] = [\hat{L}^2,\hat{L}_y] = [\hat{L}^2,\hat{L}_z] = 0
$$



## commutation rules

<img src="../img/Vector_model_of_orbital_angular_momentum.svg" width="300">

## the eignevalue equation

In order to determine the stationary state and the magnitude of the operators we need to solve the eigenvalue equation. 

In cartesian coordinates we know it will be difficult to separate the variabes so we have to *express the operators of angular momentum in the polar system*

$$
\hat{L}_x = i\hbar\left( sin\phi \frac{\partial}{\partial \theta} + cot\theta cos\phi \frac{\partial}{\partial \phi} \right)
$$
$$
\hat{L}_y = -i\hbar\left( cos\phi \frac{\partial}{\partial \theta} - cot\theta sin\phi \frac{\partial}{\partial \phi} \right)
$$
$$
\hat{L}_z = -i\hbar\frac{\partial}{\partial \phi}
$$
$$
\hat{L}^2 = -i\hbar\left( \frac{\partial^2}{\partial \theta} + cot\theta \frac{\partial}{\partial \theta} + \frac{1}{sin^2\phi}\frac{\partial^2}{\partial \phi} \right)
$$

## the eigenvalue equation

### the projection on z

$$
\hat{L}_z Y(\theta,\phi) = b Y(\theta,\phi)
$$
$$
\hat{L}^2 Y(\theta,\phi) = c Y(\theta,\phi)
$$

We can factorize the wavefunction into

$$
Y(\theta,\phi) = \Theta(\theta) \Phi(\phi)
$$

and because $\hat{L}_z$ only actuates on $\phi$ we can write the equation for the projection in $z$ as:

$$
-i\hbar\frac{\partial}{\partial \phi} Y(\theta,\phi) = b Y(\theta,\phi)
$$

We recognize this equation and know that a candidate eigenfunction is

$$
\Phi(\phi) = Ae^{ib\phi/\hbar}
$$

Using the border condition

$$
\Phi(\phi + 2\pi) = \Phi(\phi)
$$

we find that $b=m\hbar$ and $m=\ldots -2, -1, 0, 1, \ldots$

So, after normalization

$$
\Phi(\phi) = \frac{1}{\sqrt{2\pi}}e^{im\phi}
$$


### the module 

We should now use this last equation into the eigen equation for $\hat{L}^2$

$$
-i\hbar\left( \frac{\partial^2}{\partial \theta} + cot\theta \frac{\partial}{\partial \theta} + \frac{1}{sin^2\phi}\frac{\partial^2}{\partial \phi} \right) \left(\frac{1}{\sqrt{2\pi}}e^{im\phi}\right) = c \left(  \frac{1}{\sqrt{2\pi}}e^{im\phi} \right)
$$

Solving this equation we find:

$$
c = \hbar^2(k+|m|)(k+|m|+1), k = 0,1,2,\ldots
$$

Since $|m| = 0,1,2,\ldots$, then $k+|m| = 0,1,2,\ldots$

we can define $l = k+|m|$ with $l = 0,1,2,\ldots$ so
 
$$
c = \hbar^2 l(l+1), l = 0,1,2,\ldots
$$

and the module $|\mathbf{L}|$ is $\hbar \sqrt{l(l+1)}$

Since we defined $l = k+|m|$

$$
m = -l, -l-1,-l-2,\ldots,-1,0,1,\ldots,l-2,l-1,l
$$




$$
b = m\hbar, m=0,\pm 1, \pm 2, \ldots
$$

$$
\sqrt{c} = \hbar \sqrt{l(l+1)}, l = 0,1,2,\ldots
$$
<img src="../img/angularMomentumEignenValues.png" width="300">


$$
Y_{0}^0(\theta,\phi) = \frac{1}{\sqrt{4\pi}}
$$

so the eigenfunctions for the angular momentum are the spherial harmonics

## degenerated states

<img src="../img/angularMomentumDegeneratedStates.png" width="500">

# spin and spin-orbits

## the spin

Remember the Stern ad Gerlach experiment?

Another angular momentum exists: **THE SPIN**

It has no "classical" equivalence, but it is still there and we can observe it. Since it behave like an angular momentum, we can define the following opertors in analogy to what we did for the orbital angular momentum.

$$
\hat{S}^2 = \hat{S}_x^2+ \hat{S}_y^2 + \hat{S}_z^2
$$

$$
[\hat{S}_x,\hat{S}_y] = i\hbar \hat{S}_z
$$

$$
[\hat{S}_y,\hat{S}_z] = i\hbar \hat{S}_x
$$

$$
[\hat{S}_z,\hat{S}_x] = i\hbar \hat{S}_y
$$

and

$$
[\hat{S}^2,\hat{S}_x] = [\hat{S}^2,\hat{S}_y] = [\hat{S}^2,\hat{S}_z] = 0
$$



The commutations rules are very important. How can we remember them easily?

As rotations in $\mathbb{R}^3$!! (Lie Group)

## eigen equation for the spin 1/2

$$
\hat{S}_z \alpha = \hbar m_s =\frac{1}{2}\hbar \alpha
$$
$$
\hat{S}_z \beta = \hbar m_s = -\frac{1}{2}\hbar \beta
$$

where for $S=\frac{1}{2}$, $m_s=-s,-s-1,\ldots,0,1,\ldots, s = -\frac{1}{2}, \frac{1}{2}$

y 

$$
\hat{S}^2 \alpha = \hbar^2 s(s+1) =\frac{1}{2}\left(\frac{3}{2}\right)\hbar^2 \alpha
$$

$$
\hat{S}^2 \beta = \hbar^2 s(s+1) =\frac{1}{2}\left(\frac{3}{2}\right)\hbar^2 \beta
$$


## Pauli matrices


In [103]:
from numpy import *
from matplotlib.pyplot import *

# we can define four Pauli matrices for the four Spin Operators
Sx = .5* matrix('0 1;1 0')
Sy = .5* matrix('0 0.-1.j;0.+1.j 0')
Sz = .5* matrix('1 0;0 -1')
Ssq = .25* matrix('3 0;0 3')
print('Sx:')
print(Sx)
print('norm of (Sx)^2:')
print(trace((Sx**2)))


Sx:
[[ 0.   0.5]
 [ 0.5  0. ]]
norm of (Sx)^2:
0.5


In [3]:
# we can play with these matrix to find out the commutation rules
print('the commutator [Sx,Sy]=')
print(Sx*Sy-Sy*Sx)
print('which is equal to i*Sz')
print(0.+1.j * Sz)
print('the commutator [S^2,Sy]=')
print(Ssq*Sy-Sy*Ssq)
# as expected!

the commutator [Sx,Sy]=
[[ 0.+0.5j  0.+0.j ]
 [ 0.+0.j   0.-0.5j]]
which is equal to i*Sz
[[ 0.+0.5j  0.+0.j ]
 [ 0.+0.j   0.-0.5j]]
the commutator [S^2,Sy]=
[[ 0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j]]


In [4]:
alpha = matrix('1;0')
beta = matrix('0;1')

print(Sz*alpha)
print(Sz*beta)
print(Ssq*alpha)
print(Ssq*beta)

[[ 0.5]
 [ 0. ]]
[[ 0. ]
 [-0.5]]
[[ 0.75]
 [ 0.  ]]
[[ 0.  ]
 [ 0.75]]


## spin-orbit coupling

there are two angular momenta, thus two diplolar momenta

$$
J = |L+S|
$$

<img src="../img/LS_coupling.svg" width="300">



## the $H_{S-O}$ *Hamiltonian*

we need to include the S-O interaction term in the *Hamiltonian*

$$
\hat{H} = \hat{H}_{0}+\hat{H}_{SO}
$$

$$
\hat{H}_{SO} = \frac{\kappa e^2 Z}{2m^2c^2}\frac{LS}{r^3}
$$

The important part of that term is the product $LS$ that means that the magnitud of the interaction will depend on the orientation (dot product depends on the cosine)

The **consequence** is that $m_l$ and $m_s$ are not any more good quantum number and we have to introduce $j$ and $m_j$ instead.

The sum of the two angular momenta is:

$$
J=L+S, L+S-1, \ldots, |L-S|
$$

and

$$
m_j = -J, -J+1, \ldots, J
$$

## configuration...

### spectroscopic terms, nivels & states

Look at the configuration $1s^1$ for the hydrogen atom. There are only two ways to combine the angular momenta $L=0$ and $S=\frac{1}{2}$:

$$
J = 0+\frac{1}{2} = \frac{1}{2}
$$

There is thus 1 levels:

$$
^{2s+1}L_j = ^2S_{\frac{1}{2}}
$$

and $(2j+1)=2$ degenerate states with $m_j=-\frac{1}{2},\frac{1}{2}$

If the configuration is $2p^1$, for an excited state, then we would have $L=1$ and $S=\frac{1}{2}$. Thus 

$$
J = 1+\frac{1}{2}, 1+\frac{1}{2}-1 = \frac{3}{2},\frac{1}{2}
$$

and the 2 levels are  $^2P_{\frac{3}{2}}$ ($(2j+1)=4$ states), $^2P_{\frac{1}{2}}$ ($(2j+1)=2$ states) with a total of 6 states.


another way to see this is to look for all the possible states.

For example in the case of the configuration $1s^1$ the angular momentum $L$ has only one possible value $m_l=0$ and the spin has 2 possible values $m_s=-1/2,1/2$. How many different states can we build? 2

|      | 0 |
|------|---|
| 1/2  | {0,1/2} |
| -1/2 | {0,-1/2}|

While for the $2p^1$

we have 6 states

|      | 1 | 0 | -1 |
|------|---|---|----|
| 1/2  |{1,1/2}|{0,1/2}|{-1,1/2}|
| -1/2 |{1,-1/2}|{0,-1/2}|{-1,-1/2}|

since the maximum value $m_j = m_l+m_s = 3/2$ we know that we have $J=3/2$ with four states ${3/2,1/2,-1/2,-3/2}$. If we remove these 4 values from the table we found two remaining ${1/2,-1/2}$ meaning we have another value $J=1/2$. So we have 2 levels $^2P_{\frac{1}{2}}$ and $2^P_{\frac{3}{2}}$


## selection rules

<img src="../img/SOCoupling.png" width="600">
<img src="../img/SODoublets.png" width="600">

#### With the following selection rules

$$
\Delta l=\pm 1
$$
$$
\Delta j=0, \pm 1
$$
$$
\Delta m_j=0, \pm 1
$$


## Zeeman effect
<img src="../img/zeeman.png" width="500">